platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
pod 'QRCodeReader.swift', '~> 5.2.1'

source 'https://github.com/CocoaPods/Specs.git'
pod 'Alamofire', '~> 3.0'

pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"

